---
# tasks file for symfony2
- name: Create the release {{symfony2_project_release}} directory.
  file: state=directory path={{symfony2_project_root}}/releases/{{symfony2_project_release}}

- name: Create the shared directory
  file: state=directory path={{symfony2_project_root}}/shared

- name: Create the shared directories
  file: state=directory path={{ symfony2_project_root }}/shared/{{ item }}
  with_items: shared_directories

#- name: Create the shared/app/logs directory.
#  file: state=directory path={{symfony2_project_root}}/shared/app/logs

- name: Pull sources from the repository.
  git: repo={{symfony2_project_repo}} dest={{symfony2_project_root}}/releases/{{symfony2_project_release}} version={{symfony2_project_branch}} accept_hostkey=yes

- name: Create app/logs symlink
  file: state=link src={{symfony2_project_root}}/shared/logs path={{symfony2_project_root}}/releases/{{symfony2_project_release}}/app/logs

- name: Create web/uploads symlink
  file: state=link src={{symfony2_project_root}}/shared/uploads path={{symfony2_project_root}}/releases/{{symfony2_project_release}}/web/uploads

- name: Install composer
  get_url: url=https://getcomposer.org/composer.phar dest={{symfony2_project_root}}/composer.phar mode=0755 validate_certs=no

- name: Run composer install
  shell: cd {{symfony2_project_root}}/releases/{{symfony2_project_release}} && {{symfony2_project_php_path}} {{symfony2_project_root}}/composer.phar install {{symfony2_project_composer_opts}}

#- name: Dump assets
#  shell: cd {{symfony2_project_root}}/releases/{{symfony2_project_release}} && {{symfony2_project_php_path}} app/console assetic:dump --env={{symfony2_project_env}} {{symfony2_project_console_opts}}

- name: Create symlink
  file: state=link src={{symfony2_project_root}}/releases/{{symfony2_project_release}} path={{symfony2_project_root}}/release


# todo: userfiles symlink, resources, sessions?
# versioned path (commit to /web)
